- name: Run Backend Application
  community.docker.docker_container:
    name: my-api
    image: azekyo/tp-devops-api	
    env:
      DATABASE_HOST: my-db  # Name of the database container
      DATABASE_PORT: "5432"  # Default PostgreSQL port
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    networks:
      - name: my-network
    state: started

